apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: complex.workflow2-gitops
  namespace: orchestrator-gitops
  labels:
    app-type: workflow
    app: complex.workflow2
spec:
  destination:
    namespace: sonataflow-infra
    server: https://kubernetes.default.svc
  project: orchestrator-gitops
  source:
    path: ./kustomize/base
    repoURL: git@github.com:gabriel-farache/complex-workflow2-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
